# SPDX-FileCopyrightText: 2026 Henrique Freire <hfreire10@hotmail.com>

# SPDX-License-Identifier: MIT

# Debug
CONFIG_STACK_CANARIES=y
CONFIG_STACK_SENTINEL=y

# General
CONFIG_LOG=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_FLASH=y
CONFIG_EVENTS=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_IDLE_STACK_SIZE=256
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=102400
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Bootloader
# CONFIG_IMG_MANAGER=y
# CONFIG_MCUBOOT_IMG_MANAGER=y

# Networking
CONFIG_NET_UDP=y
CONFIG_NET_IPV4=y
CONFIG_POSIX_API=y
CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_TX_STACK_SIZE=4096
CONFIG_NET_RX_STACK_SIZE=4096
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096

## LoRa
CONFIG_LORA=y

## DHCP
CONFIG_NET_DHCPV4_SERVER=y
CONFIG_NET_DHCPV4_SERVER_ADDR_COUNT=8
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_AUTO_INIT=y
CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.5.1"
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.5.1"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"

## WiFi
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_ESP32_WIFI_IRAM_OPT=y
CONFIG_ESP32_WIFI_RX_IRAM_OPT=y
CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=48
#default value in seconds
CONFIG_WIFI_MGMT_AP_STA_INACTIVITY_TIMEOUT=300

# SD Card
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FAT_FILESYSTEM_ELM=y
