# SPDX-FileCopyrightText: 2026 Henrique Freire <hfreire10@hotmail.com>

# SPDX-License-Identifier: MIT

# Wi-Fi credentials
CONFIG_WIFI_EAP_ID=
CONFIG_WIFI_EAP_PASSWD=

# Google Apps Script
CONFIG_SERVER_URL=
CONFIG_SERVER_HOST=
CONFIG_SERVER_SECRET=

# UpdateHub access
CONFIG_UPDATEHUB_PRODUCT_UID=
